### ISSUE TITLE
Please mark the mod as compatible with Minecraft 1.16.5 on CurseForge

### ISSUE THREAD

**Issue by Kasualix** [suppergerrie2/AlwaysEat#2]
[This file](https://www.curseforge.com/minecraft/mc-mods/alwayseat/files/3029584) is perfectly compatible with Minecraft 1.16.5 but the CurseForge APP doesn't allow it to be installed in a 1.16.5 modpack:
![image](https://user-images.githubusercontent.com/110756250/188169994-b2d9a004-7084-4538-b08e-c8164425e335.png)
It would be nice if you can do that.

**Comment by suppergerrie2** [comment]
I'm gonna take your word for it since I have no way of testing it right now ;)
I put it on all subversion of 1.16, let me know if it breaks!
